<a href="https://colab.research.google.com/github/Triiplech4554/pyton_dataviz2023/blob/main/HW_2_2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### HW2 สร้าง logo พรรคก้าวไกล

In [70]:
import numpy as np
Mfp = np.ones((14,12))
Mfp[0:2,0:12] = 99
Mfp[2,10:12] =99
Mfp[3:5,9:10] =99
Mfp[3:5,10:11] =99
Mfp[5:7,8:10] =99
Mfp[7:9,7:9] =99
Mfp[9:11,6:8] =99
Mfp[11:13,5:7] =99
Mfp[3:5,4:6] =99
#########################
Mfp[3:5,1:8] = 99
Mfp[5:7,5:7] = 99
Mfp[7:9,4:6] = 99
Mfp[9:11,3:5] = 99
print(Mfp)


[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 99. 99.]
 [ 1. 99. 99. 99. 99. 99. 99. 99.  1. 99. 99.  1.]
 [ 1. 99. 99. 99. 99. 99. 99. 99.  1. 99. 99.  1.]
 [ 1.  1.  1.  1.  1. 99. 99.  1. 99. 99.  1.  1.]
 [ 1.  1.  1.  1.  1. 99. 99.  1. 99. 99.  1.  1.]
 [ 1.  1.  1.  1. 99. 99.  1. 99. 99.  1.  1.  1.]
 [ 1.  1.  1.  1. 99. 99.  1. 99. 99.  1.  1.  1.]
 [ 1.  1.  1. 99. 99.  1. 99. 99.  1.  1.  1.  1.]
 [ 1.  1.  1. 99. 99.  1. 99. 99.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 99. 99.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 99. 99.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### HW2.5 เราสร้าง function print logo พรรคก้าวไกลโดย input พื้นหลังได้

In [78]:
def print_Mfp(Mfp,background,ph):
    for Array in Mfp:
        for num in Array:
            if num == 1:
                print(background, end='   ')
            else:
                print(ph, end=' ')
        print()
background = '*'
ph = 'Mfp' #รูป

print_Mfp(Mfp,background,ph )

Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp 
Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp Mfp 
*   *   *   *   *   *   *   *   *   *   Mfp Mfp 
*   Mfp Mfp Mfp Mfp Mfp Mfp Mfp *   Mfp Mfp *   
*   Mfp Mfp Mfp Mfp Mfp Mfp Mfp *   Mfp Mfp *   
*   *   *   *   *   Mfp Mfp *   Mfp Mfp *   *   
*   *   *   *   *   Mfp Mfp *   Mfp Mfp *   *   
*   *   *   *   Mfp Mfp *   Mfp Mfp *   *   *   
*   *   *   *   Mfp Mfp *   Mfp Mfp *   *   *   
*   *   *   Mfp Mfp *   Mfp Mfp *   *   *   *   
*   *   *   Mfp Mfp *   Mfp Mfp *   *   *   *   
*   *   *   *   *   Mfp Mfp *   *   *   *   *   
*   *   *   *   *   Mfp Mfp *   *   *   *   *   
*   *   *   *   *   *   *   *   *   *   *   *   
